import type { GlobalThemeOverrides } from 'naive-ui'
import { lightTokens, darkTokens } from './tokens'

export const lightTheme: GlobalThemeOverrides = {
  common: {
    primaryColor: lightTokens.primary,
    primaryColorHover: '#8b5cf6',
    primaryColorPressed: '#6d28d9',
    primaryColorSuppl: '#8b5cf6',
    bodyColor: lightTokens.bg,
    cardColor: lightTokens.surface,
    modalColor: lightTokens.surface,
    popoverColor: lightTokens.surface,
    borderRadius: lightTokens.radius,
    borderRadiusSmall: lightTokens.radiusSm,
    boxShadow1: lightTokens.shadow,
    boxShadow2: lightTokens.shadow,
    successColor: lightTokens.success,
    successColorHover: '#34d399',
    successColorPressed: '#059669',
    successColorSuppl: '#34d399',
    errorColor: lightTokens.error,
    errorColorHover: '#ef4444',
    errorColorPressed: '#b91c1c',
    errorColorSuppl: '#ef4444',
    warningColor: lightTokens.warning,
    warningColorHover: '#fbbf24',
    warningColorPressed: '#d97706',
    warningColorSuppl: '#fbbf24',
    infoColor: lightTokens.info,
    infoColorHover: '#60a5fa',
    infoColorPressed: '#2563eb',
    infoColorSuppl: '#60a5fa',
    borderColor: lightTokens.border,
    dividerColor: lightTokens.border,
    inputColor: lightTokens.surface,
    tableColor: lightTokens.surface,
    hoverColor: 'rgba(124,58,237,0.06)',
    pressedColor: 'rgba(124,58,237,0.12)',
  },
  Card: {
    paddingMedium: '20px',
    borderRadius: '14px',
    color: lightTokens.surface,
    borderColor: lightTokens.border,
  },
  Button: {
    borderRadiusMedium: '8px',
    fontWeight: '600',
  },
  Input: {
    borderRadius: '8px',
  },
}

export const darkTheme: GlobalThemeOverrides = {
  common: {
    primaryColor: darkTokens.primary,
    primaryColorHover: '#8b5cf6',
    primaryColorPressed: '#6d28d9',
    primaryColorSuppl: '#8b5cf6',
    bodyColor: darkTokens.bg,
    cardColor: darkTokens.surface,
    modalColor: darkTokens.surface,
    popoverColor: darkTokens.surface,
    borderRadius: darkTokens.radius,
    borderRadiusSmall: darkTokens.radiusSm,
    boxShadow1: darkTokens.shadow,
    boxShadow2: darkTokens.shadow,
    successColor: darkTokens.success,
    successColorHover: '#34d399',
    successColorPressed: '#059669',
    successColorSuppl: '#34d399',
    errorColor: darkTokens.error,
    errorColorHover: '#ef4444',
    errorColorPressed: '#b91c1c',
    errorColorSuppl: '#ef4444',
    warningColor: darkTokens.warning,
    warningColorHover: '#fbbf24',
    warningColorPressed: '#d97706',
    warningColorSuppl: '#fbbf24',
    infoColor: darkTokens.info,
    infoColorHover: '#60a5fa',
    infoColorPressed: '#2563eb',
    infoColorSuppl: '#60a5fa',
    borderColor: darkTokens.border,
    dividerColor: darkTokens.border,
    inputColor: darkTokens.surface,
    tableColor: darkTokens.surface,
    hoverColor: 'rgba(124,58,237,0.10)',
    pressedColor: 'rgba(124,58,237,0.16)',
  },
  Card: {
    paddingMedium: '20px',
    borderRadius: '14px',
    color: darkTokens.surface,
    borderColor: darkTokens.border,
  },
  Button: {
    borderRadiusMedium: '8px',
    fontWeight: '600',
  },
  Input: {
    borderRadius: '8px',
  },
}
