/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capabilities */
        get: operations["get_capabilities_api_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        /** Update Config */
        put: operations["update_config_api_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config Meta */
        get: operations["get_config_meta_api_config_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crawl/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Crawl Index */
        post: operations["api_crawl_index_api_crawl_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/detect-page-type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Detect Page Type */
        post: operations["api_detect_page_type_api_detect_page_type_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explore/download-magnet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explore Download Magnet */
        post: operations["explore_download_magnet_api_explore_download_magnet_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explore/index-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explore Index Status */
        post: operations["explore_index_status_api_explore_index_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explore/one-click": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explore One Click */
        post: operations["explore_one_click_api_explore_one_click_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explore/proxy-page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explore Proxy Page */
        get: operations["explore_proxy_page_api_explore_proxy_page_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explore/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explore Resolve */
        post: operations["explore_resolve_api_explore_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explore/search-by-video-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explore Search By Video Code */
        post: operations["explore_search_by_video_code_api_explore_search_by_video_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/explore/sync-cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explore Sync Cookie */
        post: operations["explore_sync_cookie_api_explore_sync_cookie_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Health Check */
        post: operations["run_health_check_api_health_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/spider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Submit Spider Job */
        post: operations["api_submit_spider_job_api_jobs_spider_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Get Spider Job Status */
        get: operations["api_get_spider_job_status_api_jobs__job_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Javdb Session */
        post: operations["refresh_javdb_session_api_login_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Complete */
        post: operations["mark_complete_api_onboarding_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/dismiss-hint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Hint */
        post: operations["dismiss_hint_api_onboarding_dismiss_hint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_onboarding_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Component */
        post: operations["test_component_api_onboarding_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Parse Category */
        post: operations["api_parse_category_api_parse_category_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Parse Detail */
        post: operations["api_parse_detail_api_parse_detail_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Parse Index */
        post: operations["api_parse_index_api_parse_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Parse Tags */
        post: operations["api_parse_tags_api_parse_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Parse Top */
        post: operations["api_parse_top_api_parse_top_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Parse Url */
        post: operations["api_parse_url_api_parse_url_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Detail */
        get: operations["get_session_detail_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Commit */
        post: operations["post_commit_api_sessions__session_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Rollback */
        post: operations["post_rollback_api_sessions__session_id__rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State */
        get: operations["get_state_api_system_state_get"];
        /** Put State */
        put: operations["put_state_api_system_state_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/adhoc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Adhoc */
        post: operations["trigger_adhoc_api_tasks_adhoc_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Daily */
        post: operations["trigger_daily_api_tasks_daily_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Stats */
        get: operations["task_stats_api_tasks_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_tasks__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Stream */
        get: operations["get_task_stream_api_tasks__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdhocTaskPayload */
        AdhocTaskPayload: {
            /**
             * Date Filter
             * @default false
             */
            date_filter: boolean;
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
            /**
             * End Page
             * @default 1
             */
            end_page: number;
            /**
             * History Filter
             * @default false
             */
            history_filter: boolean;
            /**
             * Ignore Release Date
             * @default true
             */
            ignore_release_date: boolean;
            /** Max Movies Phase1 */
            max_movies_phase1?: number | null;
            /** Max Movies Phase2 */
            max_movies_phase2?: number | null;
            /**
             * No Proxy
             * @default false
             */
            no_proxy: boolean;
            /**
             * Phase
             * @default all
             */
            phase: string;
            /** Qb Category */
            qb_category?: string | null;
            /**
             * Start Page
             * @default 1
             */
            start_page: number;
            /** Url */
            url: string;
            /**
             * Use Proxy
             * @default false
             */
            use_proxy: boolean;
        };
        /** Build */
        Build: {
            /** Backend Version */
            backend_version: string;
            /** Frontend Version */
            frontend_version?: string | null;
            /** Git Sha */
            git_sha: string;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            build: components["schemas"]["Build"];
            /**
             * Deployment
             * @enum {string}
             */
            deployment: "colocated" | "split" | "unknown";
            features: components["schemas"]["Features"];
            gh_actions: components["schemas"]["GhActions"];
            /**
             * Ingestion Mode
             * @enum {string}
             */
            ingestion_mode: "local" | "github" | "dual";
            /**
             * Storage Backend
             * @enum {string}
             */
            storage_backend: "sqlite" | "d1" | "dual";
            /**
             * Version
             * @description Capabilities schema version
             * @default 2.0.0
             */
            version: string;
        };
        /** ChangePasswordPayload */
        ChangePasswordPayload: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * ConfigResponse
         * @description GET /api/config returns the masked runtime config dict verbatim.
         */
        ConfigResponse: {
            [key: string]: unknown;
        };
        /** CrawlIndexPayload */
        CrawlIndexPayload: {
            /**
             * Crawl All
             * @default false
             */
            crawl_all: boolean;
            /** End Page */
            end_page?: number | null;
            /**
             * Max Consecutive Empty
             * @default 2
             */
            max_consecutive_empty: number;
            /**
             * Page Delay
             * @default 1
             */
            page_delay: number;
            /**
             * Start Page
             * @default 1
             */
            start_page: number;
            /** Url */
            url: string;
            /**
             * Use Cf Bypass
             * @default true
             */
            use_cf_bypass: boolean;
            /**
             * Use Cookie
             * @default false
             */
            use_cookie: boolean;
            /**
             * Use Proxy
             * @default true
             */
            use_proxy: boolean;
        };
        /** DailyTaskPayload */
        DailyTaskPayload: {
            /**
             * All
             * @default false
             */
            all: boolean;
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
            /**
             * End Page
             * @default 10
             */
            end_page: number;
            /**
             * Ignore History
             * @default false
             */
            ignore_history: boolean;
            /**
             * Ignore Release Date
             * @default false
             */
            ignore_release_date: boolean;
            /** Max Movies Phase1 */
            max_movies_phase1?: number | null;
            /** Max Movies Phase2 */
            max_movies_phase2?: number | null;
            /**
             * Mode
             * @default pipeline
             */
            mode: string;
            /**
             * No Proxy
             * @default false
             */
            no_proxy: boolean;
            /** Output File */
            output_file?: string | null;
            /**
             * Phase
             * @default all
             */
            phase: string;
            /**
             * Pikpak Individual
             * @default false
             */
            pikpak_individual: boolean;
            /**
             * Start Page
             * @default 1
             */
            start_page: number;
            /**
             * Use Proxy
             * @default false
             */
            use_proxy: boolean;
        };
        /** DismissHintPayload */
        DismissHintPayload: {
            /** Hint Id */
            hint_id: string;
        };
        /** ExploreCookiePayload */
        ExploreCookiePayload: {
            /** Cookie */
            cookie: string;
        };
        /** ExploreIndexStatusItem */
        ExploreIndexStatusItem: {
            /** Downloaded */
            downloaded: boolean;
            /** Has Uncensored */
            has_uncensored: boolean;
        } & {
            [key: string]: unknown;
        };
        /** ExploreIndexStatusPayload */
        ExploreIndexStatusPayload: {
            /** Movies */
            movies?: {
                [key: string]: string;
            }[];
            /**
             * Use Cookie
             * @default true
             */
            use_cookie: boolean;
            /**
             * Use Proxy
             * @default true
             */
            use_proxy: boolean;
        };
        /** ExploreIndexStatusResponse */
        ExploreIndexStatusResponse: {
            /** Items */
            items: {
                [key: string]: components["schemas"]["ExploreIndexStatusItem"];
            };
        } & {
            [key: string]: unknown;
        };
        /** ExploreMagnetPayload */
        ExploreMagnetPayload: {
            /** Category */
            category?: string | null;
            /** Magnet */
            magnet: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** ExploreOneClickPayload */
        ExploreOneClickPayload: {
            /** Category */
            category?: string | null;
            /** Detail Url */
            detail_url: string;
            /**
             * Use Cookie
             * @default true
             */
            use_cookie: boolean;
            /**
             * Use Proxy
             * @default true
             */
            use_proxy: boolean;
        };
        /** ExploreOneClickResponse */
        ExploreOneClickResponse: {
            /** Selected */
            selected?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /** Video Code */
            video_code?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ExploreResolvePayload */
        ExploreResolvePayload: {
            /**
             * Page Num
             * @default 1
             */
            page_num: number;
            /** Url */
            url: string;
            /**
             * Use Cookie
             * @default true
             */
            use_cookie: boolean;
            /**
             * Use Proxy
             * @default true
             */
            use_proxy: boolean;
        };
        /** ExploreResolveResponse */
        ExploreResolveResponse: {
            /** Detail */
            detail?: {
                [key: string]: unknown;
            } | null;
            /** Index */
            index?: {
                [key: string]: unknown;
            } | null;
            /** Page Type */
            page_type: string;
            /** Url */
            url: string;
        } & {
            [key: string]: unknown;
        };
        /** Features */
        Features: {
            /** Javdb Login */
            javdb_login: boolean;
            /** Pikpak */
            pikpak: boolean;
            /** Proxy Pool */
            proxy_pool: boolean;
            /** Proxy Preview */
            proxy_preview: boolean;
            /** Rclone */
            rclone: boolean;
            /** Smtp */
            smtp: boolean;
        };
        /** GhActions */
        GhActions: {
            /** Repo */
            repo: string | null;
            /**
             * Tier
             * @enum {string}
             */
            tier: "none" | "monitor" | "edit" | "admin";
            /** Token Configured */
            token_configured: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheckPayload */
        HealthCheckPayload: {
            /**
             * Check Smtp
             * @default true
             */
            check_smtp: boolean;
            /**
             * No Proxy
             * @default false
             */
            no_proxy: boolean;
            /**
             * Use Proxy
             * @default false
             */
            use_proxy: boolean;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Rust Core Available
             * @default false
             */
            rust_core_available: boolean;
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** HtmlPayload */
        HtmlPayload: {
            /** Html */
            html: string;
            /**
             * Page Num
             * @default 1
             */
            page_num: number;
        };
        /**
         * JavdbLoginRefreshPayload
         * @description Optional request body for POST /api/login/refresh.
         *
         *     Empty body (or omitted body) defaults to proxy_mode='auto', which preserves
         *     the original behavior. Existing callers that POST without a body still work.
         */
        JavdbLoginRefreshPayload: {
            /** Max Attempts */
            max_attempts?: number | null;
            /** Pool Names */
            pool_names?: string[] | null;
            /**
             * Proxy Mode
             * @default auto
             * @enum {string}
             */
            proxy_mode: "auto" | "none" | "single" | "pool";
            /** Proxy Url */
            proxy_url?: string | null;
        };
        /**
         * JavdbLoginRefreshResponseV2
         * @description Structured response for POST /api/login/refresh with categorized errors.
         */
        JavdbLoginRefreshResponseV2: {
            /**
             * Attempts
             * @default []
             */
            attempts: {
                [key: string]: unknown;
            }[];
            /** Error Category */
            error_category?: ("invalid_credentials" | "ip_banned" | "captcha_failed" | "cloudflare_blocked" | "connection_error" | "no_credentials" | "no_proxy_succeeded" | "unknown") | null;
            /** Message */
            message: string;
            /**
             * Output
             * @default
             */
            output: string;
            /** Proxy Used */
            proxy_used?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "failed";
        };
        /**
         * JobSummaryResponse
         * @description Per-job summary returned by /api/tasks endpoints.
         */
        JobSummaryResponse: {
            /** Command */
            command?: string[] | null;
            /** Completed At */
            completed_at?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Job Id */
            job_id: string;
            /** Kind */
            kind?: string | null;
            /** Log */
            log?: string | null;
            /** Log Size */
            log_size?: number | null;
            /** Mode */
            mode?: string | null;
            /** Source */
            source?: string | null;
            /** Status */
            status: string;
            /** Url */
            url?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ListTasksResponse */
        ListTasksResponse: {
            next_schedule: components["schemas"]["NextScheduleInfo"];
            /** Tasks */
            tasks: components["schemas"]["JobSummaryResponse"][];
        } & {
            [key: string]: unknown;
        };
        /** LoginPayload */
        LoginPayload: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /** Csrf Token */
            csrf_token: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Token */
            refresh_token: string;
            /** Role */
            role: string;
            /** Token Type */
            token_type: string;
            /** Username */
            username: string;
        } & {
            [key: string]: unknown;
        };
        /** NextScheduleInfo */
        NextScheduleInfo: {
            /** Cron Pipeline */
            cron_pipeline: string;
            /** Cron Spider */
            cron_spider: string;
            /** Source */
            source: string;
        } & {
            [key: string]: unknown;
        };
        /** OnboardingStatusResponse */
        OnboardingStatusResponse: {
            /** Completed */
            completed: boolean;
            /** Required Missing */
            required_missing: string[];
            /** Skippable Missing */
            skippable_missing: string[];
        };
        /** OnboardingTestPayload */
        OnboardingTestPayload: {
            /**
             * Component
             * @enum {string}
             */
            component: "javdb" | "qb" | "proxy" | "smtp";
        };
        /** OnboardingTestResponse */
        OnboardingTestResponse: {
            /** Component */
            component: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
            /** Ok */
            ok: boolean;
        };
        /** RefreshTokenResponse */
        RefreshTokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Token Type */
            token_type: string;
        } & {
            [key: string]: unknown;
        };
        /** SessionCommitPayload */
        SessionCommitPayload: {
            /**
             * Drop Pending
             * @default false
             */
            drop_pending: boolean;
            /**
             * Emit Metrics
             * @default true
             */
            emit_metrics: boolean;
            /**
             * Fanout Claims
             * @default true
             */
            fanout_claims: boolean;
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /** SessionCommitResponse */
        SessionCommitResponse: {
            /** New State */
            new_state: string;
            /**
             * Pending Dropped
             * @default 0
             */
            pending_dropped: number;
            /** Session Id */
            session_id: string;
        };
        /** SessionDetailResponse */
        SessionDetailResponse: {
            /** Movies */
            movies: {
                [key: string]: unknown;
            }[];
            session: components["schemas"]["SessionItem"];
            /** Torrents */
            torrents: {
                [key: string]: unknown;
            }[];
        };
        /** SessionItem */
        SessionItem: {
            /** Created At */
            created_at: string;
            /** Run Attempt */
            run_attempt: number | null;
            /** Run Id */
            run_id: string | null;
            /** Session Id */
            session_id: string;
            /** State */
            state: string;
            /** Write Mode */
            write_mode: string;
        };
        /** SessionListResponse */
        SessionListResponse: {
            /** Items */
            items: components["schemas"]["SessionItem"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total Estimate */
            total_estimate?: number | null;
        };
        /** SessionRollbackPayload */
        SessionRollbackPayload: {
            /**
             * Dry Run
             * @default true
             */
            dry_run: boolean;
            /**
             * Include Pending
             * @default true
             */
            include_pending: boolean;
            /**
             * Restore From Audit
             * @default true
             */
            restore_from_audit: boolean;
        };
        /** SessionRollbackResponse */
        SessionRollbackResponse: {
            /** Actions */
            actions: {
                [key: string]: unknown;
            }[];
            /** Dry Run */
            dry_run: boolean;
            /** Session Id */
            session_id: string;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /** SpiderJobPayload */
        SpiderJobPayload: {
            /**
             * Crawl All
             * @default false
             */
            crawl_all: boolean;
            /**
             * Disable All Filters
             * @default false
             */
            disable_all_filters: boolean;
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
            /**
             * Enable Dedup
             * @default false
             */
            enable_dedup: boolean;
            /**
             * Enable Redownload
             * @default false
             */
            enable_redownload: boolean;
            /** End Page */
            end_page?: number | null;
            /**
             * Ignore History
             * @default false
             */
            ignore_history: boolean;
            /**
             * Ignore Release Date
             * @default false
             */
            ignore_release_date: boolean;
            /** Max Movies Phase1 */
            max_movies_phase1?: number | null;
            /** Max Movies Phase2 */
            max_movies_phase2?: number | null;
            /**
             * No Proxy
             * @default false
             */
            no_proxy: boolean;
            /**
             * No Rclone Filter
             * @default false
             */
            no_rclone_filter: boolean;
            /**
             * Phase
             * @default all
             * @enum {string}
             */
            phase: "1" | "2" | "all";
            /** Redownload Threshold */
            redownload_threshold?: number | null;
            /**
             * Start Page
             * @default 1
             */
            start_page: number;
            /** Url */
            url?: string | null;
            /**
             * Use History
             * @default false
             */
            use_history: boolean;
            /**
             * Use Proxy
             * @default false
             */
            use_proxy: boolean;
        };
        /** SpiderJobStatusResponse */
        SpiderJobStatusResponse: {
            /** Cli Args */
            cli_args: string[];
            /** Csv Path */
            csv_path?: string | null;
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Job Id */
            job_id: string;
            /** Output */
            output?: string[] | null;
            /** Pid */
            pid?: number | null;
            /** Return Code */
            return_code?: number | null;
            /** Session Id */
            session_id?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** SpiderJobSubmitResponse */
        SpiderJobSubmitResponse: {
            /** Cli Args */
            cli_args: string[];
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** StatusOkResponse */
        StatusOkResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** SystemStateGetResponse */
        SystemStateGetResponse: {
            /** Key */
            key: string;
            /** Value */
            value: string | null;
        };
        /** SystemStatePutPayload */
        SystemStatePutPayload: {
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /** TaskStatsResponse */
        TaskStatsResponse: {
            /** Adhoc Running */
            adhoc_running: number;
            /** Daily Failed */
            daily_failed: number;
            /** Daily Running */
            daily_running: number;
            /** Daily Success */
            daily_success: number;
        } & {
            [key: string]: unknown;
        };
        /**
         * TriggerTaskResponse
         * @description Returned by POST /api/tasks/daily and POST /api/tasks/adhoc.
         */
        TriggerTaskResponse: {
            /** Created At */
            created_at: string;
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        } & {
            [key: string]: unknown;
        };
        /** UrlPayload */
        UrlPayload: {
            /**
             * Page Num
             * @default 1
             */
            page_num: number;
            /** Url */
            url: string;
            /**
             * Use Cf Bypass
             * @default true
             */
            use_cf_bypass: boolean;
            /**
             * Use Cookie
             * @default false
             */
            use_cookie: boolean;
            /**
             * Use Proxy
             * @default true
             */
            use_proxy: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VideoCodeSearchPayload */
        VideoCodeSearchPayload: {
            /**
             * F
             * @default all
             */
            f: string;
            /**
             * Use Cookie
             * @default true
             */
            use_cookie: boolean;
            /**
             * Use Proxy
             * @default true
             */
            use_proxy: boolean;
            /** Video Code */
            video_code: string;
        };
        /** VideoCodeSearchResponse */
        VideoCodeSearchResponse: {
            /** Exact Match Entry */
            exact_match_entry?: {
                [key: string]: string;
            } | null;
            /** Letter Suffix Fallback Searched */
            letter_suffix_fallback_searched: boolean;
            /** Movies */
            movies: {
                [key: string]: unknown;
            }[];
            /** Search Url */
            search_url: string;
            /** Video Code */
            video_code: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    change_password_api_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOkResponse"];
                };
            };
        };
    };
    refresh_token_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenResponse"];
                };
            };
        };
    };
    get_capabilities_api_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: {
                /** @description Admin-only: return unmasked secrets */
                include_secrets?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_config_api_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_meta_api_config_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_crawl_index_api_crawl_index_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlIndexPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_detect_page_type_api_detect_page_type_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HtmlPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explore_download_magnet_api_explore_download_magnet_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExploreMagnetPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explore_index_status_api_explore_index_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExploreIndexStatusPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExploreIndexStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explore_one_click_api_explore_one_click_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExploreOneClickPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExploreOneClickResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explore_proxy_page_api_explore_proxy_page_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explore_resolve_api_explore_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExploreResolvePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExploreResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explore_search_by_video_code_api_explore_search_by_video_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoCodeSearchPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoCodeSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explore_sync_cookie_api_explore_sync_cookie_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExploreCookiePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    run_health_check_api_health_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HealthCheckPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_submit_spider_job_api_jobs_spider_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpiderJobPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpiderJobSubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_get_spider_job_status_api_jobs__job_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpiderJobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_javdb_session_api_login_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["JavdbLoginRefreshPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JavdbLoginRefreshResponseV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_complete_api_onboarding_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingStatusResponse"];
                };
            };
        };
    };
    dismiss_hint_api_onboarding_dismiss_hint_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DismissHintPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_onboarding_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingStatusResponse"];
                };
            };
        };
    };
    test_component_api_onboarding_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingTestPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingTestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_parse_category_api_parse_category_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HtmlPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_parse_detail_api_parse_detail_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HtmlPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_parse_index_api_parse_index_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HtmlPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_parse_tags_api_parse_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HtmlPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_parse_top_api_parse_top_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HtmlPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_parse_url_api_parse_url_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UrlPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                state?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_detail_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_commit_api_sessions__session_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCommitPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCommitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_rollback_api_sessions__session_id__rollback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRollbackPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionRollbackResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_api_system_state_get: {
        parameters: {
            query: {
                key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStateGetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_state_api_system_state_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemStatePutPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStateGetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTasksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_adhoc_api_tasks_adhoc_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdhocTaskPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_daily_api_tasks_daily_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DailyTaskPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_stats_api_tasks_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatsResponse"];
                };
            };
        };
    };
    get_task_api_tasks__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_stream_api_tasks__job_id__stream_get: {
        parameters: {
            query?: {
                offset?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
