import { describe, it, expect } from "vitest";
import golden from "./fixtures/query-builders.golden.json";
import { buildMovieWhere, buildTorrentWhere } from "../routes/history";
import { buildSessionQuery } from "../routes/sessions";
import { buildStatsTrendQuery } from "../routes/stats";
import { cursorDecode } from "../services/cursor";

// ADR-018 query Contract Golden conformance.
//
// The golden is generated by the Python backend (source of truth) and vendored
// into this repo. This test runs the TS query builders over the golden's
// decoded inputs and asserts the assembled SQL + bindings match byte-for-byte
// (after normalization). A red test means the TS builder drifted from Python.

// MUST be byte-identical to the Python normalize_sql:
//   re.sub(r"\s+", " ", sql).strip()
const normalizeSql = (s: string) => s.replace(/\s+/g, " ").trim();

// The session golden carries a pre-encoded cursor (Python's base64 scheme). The
// wire-decode layer is each repo's own concern (ADR-018 scope note); here we
// decode it with the TS cursorDecode so the same `sid` flows into the builder.
function mapSessionParams(p: {
  state?: string | null;
  cursor?: string | null;
  limit: number;
}): { state?: string; cursor_sid?: string; limit: number } {
  return {
    state: p.state ?? undefined,
    cursor_sid: p.cursor ? cursorDecode<{ sid: string }>(p.cursor).sid : undefined,
    limit: p.limit,
  };
}

const RUN: Record<string, (p: any) => { sql: string; bindings: (string | number)[] }> = {
  movie_filters: (p) => {
    const r = buildMovieWhere(p);
    return { sql: r.where, bindings: r.bindings };
  },
  torrent_filters: (p) => {
    const r = buildTorrentWhere(p);
    return { sql: r.where, bindings: r.bindings };
  },
  session_query: (p) => buildSessionQuery(mapSessionParams(p)),
  stats_trend_query: (p) => {
    const q = buildStatsTrendQuery({ metric: p.metric, cutoff: p.cutoff });
    // The golden encodes the target DB as the first binding, followed by the
    // SQL params (mirrors the Python contract dump).
    return { sql: q.sql, bindings: [q.db, ...q.params] };
  },
};

interface GoldenCase {
  builder: string;
  name: string;
  params: any;
  sql: string;
  bindings: (string | number)[];
}

describe("ADR-018 query Contract Golden conformance", () => {
  const cases = (golden as { cases: GoldenCase[] }).cases;

  it("vendored golden has cases", () => {
    expect(Array.isArray(cases)).toBe(true);
    expect(cases.length).toBeGreaterThan(0);
  });

  for (const c of cases) {
    it(`${c.builder}:${c.name}`, () => {
      const runner = RUN[c.builder];
      expect(runner, `no TS builder mapped for '${c.builder}'`).toBeDefined();
      const { sql, bindings } = runner!(c.params);
      expect(normalizeSql(sql)).toBe(c.sql);
      expect(bindings).toEqual(c.bindings);
    });
  }
});
